### ISSUE TITLE
Adding club calender project link in project IIITV section.

### ISSUE THREAD

**Issue by nlok5923** [iiitv/resources#17]
i discovered some the issues of IIITV/club_calender has contributathon tag. Adding it's link [club_calender](https://github.com/iiitv/club_calender) the project in IIITV section will be good.

@iiitv/project-maintainers do let me know about this issue validity if this issue is valid i would like to work on it.

**Comment by yashshah2820** [comment]
I don't think it needs to be added and it needs a separate issue 🤔
