### ISSUE TITLE
Link in Footer is not correct

### ISSUE THREAD

**Issue by The-Keshav-Agarwal** [iiitv/resources#18]
link of  IIITV open source org in footer is not correct .
![image](https://user-images.githubusercontent.com/56120769/91801002-b6af5b00-ec47-11ea-825d-abad6e0167dd.png)
@iiitv/project-maintainers  I would like to work on this issue.

**Comment by ishanksoni** [comment]
@The-Keshav-Agarwal  GFI :+1:

**Comment by thepushkarp** [comment]
Fixed :+1:
