### ISSUE TITLE
Reorganise CP and DSA section

### ISSUE THREAD

**Issue by thepushkarp** [iiitv/resources#8]
Currently, the CP and DSA section is not very updated and isn't organised very well.

We need to sort things by topics, list out tutorials, articles, videos and add more things to practice section.

**Comment by thepushkarp** [comment]
Closed via #11

**Comment by RahulBansal0502** [comment]
I am happy to work on it.

**Comment by thepushkarp** [comment]
Sure, @RahulBansal0502 . Go through the list and if you have anything to add to it, send a PR 🚀.
