### ISSUE TITLE
Additions for resources

### ISSUE THREAD

**Issue by shivam0110** [iiitv/resources#9]
Documentation -  One of best static site generator( https://www.gatsbyjs.com/docs/ )
Coupons - https://www.real.discount/
Youtube Channel - DevEd ( https://www.youtube.com/channel/UClb90NQQcskPUGDIXsQEz5Q )

**Comment by thepushkarp** [comment]
Haha, no problem :P

**Comment by thepushkarp** [comment]
Resolved via #10
